# Generated by Django 2.2 on 2019-04-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
